language: ruby
rvm:
  - "1.9.3"
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database recruiting_test'
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - recruiting@gentoo.org
