language: ruby
rvm:
  - "1.9.3"
env:
  - DB=mysql
script:
  - DISPLAY=localhost:1.0 bundle exec rake spec
  - DISPLAY=localhost:1.0 bundle exec rake cucumber
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database recruiting_test'
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - Xvfb :1 -screen 0 1024x768x16 -nolisten inet6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - recruiting@gentoo.org
