language: ruby
rvm:
  - "2.1.2"
env:
  - DB=mysql
script:
  - DISPLAY=localhost:1.0 xvfb-run bundle exec rake spec
  - DISPLAY=localhost:1.0 xvfb-run bundle exec rake cucumber
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database recruiting_test'
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
  - RAILS_ENV=test bundle exec rake --trace db:migrate
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - recruiting@gentoo.org
